#ifndef AJAZZ_DEVICE_AJ179V2MAX_H
#define AJAZZ_DEVICE_AJ179V2MAX_H

#include "device.h"

/* The reference model: every capability below has been tested
 * against real hardware (see docs/reverse-engineering.md). */
static const ajazz_device_entry_t ajazz_device_aj179v2max[] = {
    {0x248A, 0x5C2E, "N625", "AJ179 V2 MAX", "USB", AJAZZ_CAP_DPI | AJAZZ_CAP_RATE | AJAZZ_CAP_RGB | AJAZZ_CAP_SENSOR | AJAZZ_CAP_KEYS | AJAZZ_CAP_BATTERY | AJAZZ_CAP_MACRO},
    {0x248A, 0x5D2E, "N625", "AJ179 V2 MAX", "USB", AJAZZ_CAP_DPI | AJAZZ_CAP_RATE | AJAZZ_CAP_RGB | AJAZZ_CAP_SENSOR | AJAZZ_CAP_KEYS | AJAZZ_CAP_BATTERY | AJAZZ_CAP_MACRO},
    {0x248A, 0x5E2E, "N625", "AJ179 V2 MAX", "USB", AJAZZ_CAP_DPI | AJAZZ_CAP_RATE | AJAZZ_CAP_RGB | AJAZZ_CAP_SENSOR | AJAZZ_CAP_KEYS | AJAZZ_CAP_BATTERY | AJAZZ_CAP_MACRO},
    {0x248A, 0x5C2F, "N625", "AJ179 V2 MAX", "2.4G", AJAZZ_CAP_DPI | AJAZZ_CAP_RATE | AJAZZ_CAP_RGB | AJAZZ_CAP_SENSOR | AJAZZ_CAP_KEYS | AJAZZ_CAP_BATTERY | AJAZZ_CAP_MACRO},
    {0x249A, 0x5C2F, "N625", "AJ179 V2 MAX", "2.4G", AJAZZ_CAP_DPI | AJAZZ_CAP_RATE | AJAZZ_CAP_RGB | AJAZZ_CAP_SENSOR | AJAZZ_CAP_KEYS | AJAZZ_CAP_BATTERY | AJAZZ_CAP_MACRO},
};
#define AJAZZ_DEVICE_AJ179V2MAX_COUNT (sizeof(ajazz_device_aj179v2max) / sizeof(ajazz_device_aj179v2max[0]))

#endif
